apiVersion: v1
appVersion: 1.0.11
description: A Helm chart for Rookout Data-On-Prem component on Kubernetes
home: http://rookout.com/
icon: https://raw.githubusercontent.com/Rookout/helm-charts/master/Rookout-logo.png
maintainers:
- email: support@rookout.com
  name: Rookout
name: datastore
version: 0.1.44
