# Default values for datastore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: rookout/data-on-prem
  pullPolicy: Always

datastore:
  serverMode: 'PLAIN'
  autoTlsDomain: ''
  tlsKeySecretName: ''
  tlsCertificateConfigmapName: ''
  token:
    tokenFromSecret:
      name: rookout-token
      key: token
  logging:
    enabled: false
  
service:
  type: ClusterIP
  loadBalancerIP: ''

pvc:
  storageClassName: hostpath
  volumeSize: 1Gi

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount: {}

ingress:
  enabled: true
  host: controller.example
  path: '/'
  servicePort: 8080
  annotations: 
    kubernetes.io/ingress.class: "nginx"