{{- if or (eq (default false .Values.datastore.inMemoryDb) false) (eq .Values.datastore.serverMode "AUTOTLS") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rookout-data-on-prem-pvc
spec:
  hostPath:
    path: /tmp/rookout
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.volumeSize }}
{{- end }}