{{- if or (eq (default false .Values.datastore.inMemoryDb) false) (eq .Values.datastore.serverMode "AUTOTLS") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rookout-data-on-prem-pvc
spec:
  hostPath:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.volumeSize }}
{{- end }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rookout-volume
  namespace: argocd
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /tmp/rookout-volume