
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: common-toolkit
spec:
  arguments:
    parameters:
    - name: something
      value: "{{workflow.parameters.something}}"
  templates:
  - name: echo-something
    inputs:
      parameters:
      - name: something
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo {{inputs.parameters.something}}