#example:
#https://github.com/argoproj/argo-events/blob/master/examples/event-sources/bitbucket.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: flask-event-source
  namespace: argocd
spec:
  eventBusName: default
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    flaskapp:
      port: "12000"
      endpoint: /
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  labels:
    k8s-app: argo-workflows
spec:
  nats:
    native:
      replicas: 3
      auth: token
      imagePullSecrets:
      - name: docker
