apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: models-templates
spec:
  templates:
  - name: tat-run
    nodeSelector:
      k8s-app: argo-workflows
    inputs:
      parameters:
      - name: working_directory
      - name: dataset_test
      - name: tat_image
      - name: sheet_name
    script:
      image: '{{inputs.parameters.tat_image}}'
      volumeMounts:
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2
        subPath: 'models2'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/categorizers
        subPath: 'categorizers'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/company_matcher/global_lei_vectorizer.pkl
        subPath: 'companymatcher/global_lei_vectorizer.pkl'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/company_matcher/global_lei_word_counter.pkl
        subPath: 'companymatcher/global_lei_word_counter.pkl'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/packages_data/fasttext_data
        subPath: 'fasttext/fasttext_data'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/packages_data/nltk_data
        subPath: 'nltk/nltk_data'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/packages_data/polyglot_data
        subPath: 'polyglot/polyglot_data'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/packages_data/spacy_data
        subPath: 'spacy/spacy_data'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /models2/shieldfc/model/packages_data/stanza_data
        subPath: 'stanza/stanza_data'
      - name: '{{inputs.parameters.working_directory}}'
        mountPath: /python_master_server_auth
        subPath: 'python_master_server_auth/python_master_server_auth'
      command: [sh]
      source: |
        . /models2/shieldfc/pre_test.sh
        export PYTHONPATH=$PYTHONPATH:/python_master_server_auth
        python /models2/shieldfc/internal/tat.py "timestemp" v0.0.0 "automtic-check" "{{inputs.parameters.dataset_test}}" "{{inputs.parameters.sheet_name}}"
        . /models2/shieldfc/post_test.sh
 