---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workflows-volume
  namespace: argocd
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /tmp/workflows-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflow-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-wf
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-wf-clusterrole
rules:
- apiGroups: ["argoproj.io"]
  resources:
  - workflows
  - workflows/finalizers
  - applications
  - appprojects
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  - pods 
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-wf-global
subjects:
- kind: ServiceAccount
  name: argo-wf
  namespace: argocd
roleRef: 
  kind: ClusterRole
  name: argo-wf-clusterrole
  apiGroup: rbac.authorization.k8s.io