repoUrl: https://github.com/GoshaDo/gitops-cluster
flaskApp:
  image: vtest-7
webapp:
  image: vtest-5

# hostAliases:
# - ip: "127.0.0.1"
#   hostnames:
#   - "controller.example"
#   - "datastore.example"

rookout:
  controller:
    host: "ws://rookout-controller.argocd.svc.cluster.local"
    port: 7488