repoUrl: https://github.com/GoshaDo/gitops-cluster
flaskApp:
  image: v0.1.7
  remoteOrigin: "https://github.com/GoshaDo/BestFW.git"
  remoteCommit: "HEAD"
webapp:
  image: vtest-6
  remoteOrigin: "https://github.com/Rookout/tutorial-python.git"
  remoteCommit: "HEAD"
# hostAliases:
# - ip: "127.0.0.1"
#   hostnames:
#   - "controller.example"
#   - "datastore.example"
rookout:
  controller:
    host: "ws://rookout-controller.argocd.svc.cluster.local"
    port: "7488"
