apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/flask-app
    repoURL: {{ .Values.repoUrl }}
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: {{ .Values.flaskApp.image }}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "false"
          host:
            - host: flask-app.example
              paths:
                - path: /
                  pathType: ImplementationSpecific