apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rookout-datastore
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/rookout-datastore
    repoURL: https://github.com/GoshaDo/gitops-cluster
    targetRevision: HEAD
    helm:
      values: |
        {{- with .Values.hostAliases }}
        hostAliases:
          {{- toYaml . | nindent 8 }}
        {{- end }}