apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/webapp
    repoURL: {{ .Values.repoUrl }}
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: {{ .Values.webapp.image }}
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: webapp.example
              paths:
                - path: /
                  pathType: ImplementationSpecific
        env: 
          - name: RO_TOKEN
            valueFrom:
              secretKeyRef:
                name: rookout-token
                key: token
          - name: ROOKOUT_CONTROLLER_HOST
            value: "{{ .Values.rookout.controller.host }}"
          - name: ROOKOUT_CONTROLLER_PORT
            value: "{{ .Values.rookout.controller.port }}"
          - name: ROOKOUT_REMOTE_ORIGIN
            value: "{{ .Values.webapp.remoteOrigin }}"
          - name: ROOKOUT_COMMIT
            value: "{{ .Values.webapp.remoteCommit }}"